### PR TITLE
Adding commands to get materials, encoded data, and cargo

### PR DESCRIPTION
**Pull request by TylerRupert**
Including the 'get-materials' api endpoint which can provide current cargo, materials, and encoded data. The response is quite lengthy, so I decided to only include items which have a quantity greater than 0.

### CODE REVIEW

**Comment by TylerRupert** [comment]
I agree. I mostly was adding the public API for fun/practice. I was adding these api endpoints from here https://www.edsm.net/en/api-commander-v1. 

I would be open to your suggestion on what information/format would be better used and I can submit a new PR with those changes

**Comment by magico13** [comment]
The commands as-is are fine, but an aggregate command might be more generally useful.

You could either modify the 'info' command or add a new command 'stats, cmdr, etc' that aggregates some of that information. Something like:
CMDR Magico13:
Location: "System ABC" 4365ly from Sol
80,987,654 credits
Cargo: 5/7
Data: 156
Ranks:
Combat: Elite (96%)
Exploration: Elite (45%)
Trade: Elite (125%)
CQC: lolwut (1337%)
Empire: None (0%) fukkin slavers
Federation: Literally the Emperor (9001%)

**Comment by magico13** [comment]
elite.py doesn't change, it just adds an additional command that makes use of the api wrapper. Also at some point elite.py should do some local caching of data like system locations (probably just a dict of system name or id and then system position) and other static data like that so it doesn't hit the api all the time for that info, if you are feeling extra bored.

**Comment by magico13** [comment]
Also we might end up wanting to make this api wrapper publicly available to people...

**Comment by TylerRupert** [comment]
Cool, good info. I probably won't be doing much more today, but will reference this when I make the next changes!

**Pull request merged**
